# Generated by Django 4.2.7 on 2025-12-02 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('voice', 'Voice Note'), ('document', 'Document')], max_length=20)),
                ('usage', models.CharField(choices=[('profile', 'Profile Image'), ('cnic', 'CNIC Document'), ('invoice', 'Invoice'), ('payment_proof', 'Payment Proof'), ('product', 'Product Image'), ('chat', 'Chat Attachment'), ('other', 'Other')], default='other', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
