# Generated by Django 6.1 on 2025-12-05 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentrecord',
            name='default_period',
            field=models.IntegerField(default=12, help_text='Default installment period in months'),
        ),
        migrations.AddField(
            model_name='installmentrecord',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Interest rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='installmentrecord',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='installmentrecord',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
