# Generated by Django 6.1 on 2025-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_installmentrecord_default_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('paused', 'Paused')], default='active', max_length=20),
        ),
    ]
