# Generated by Django 4.2.7 on 2025-12-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopkeeper',
            field=models.ForeignKey(limit_choices_to={'user_type': 'shopkeeper'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='core.product'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='shopkeeper',
            field=models.ForeignKey(limit_choices_to={'user_type': 'shopkeeper'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_installment_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='installment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.installmentplan'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shopkeeper'], name='products_shopkee_e0217e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['shopkeeper'], name='installment_shopkee_65feb0_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['buyer'], name='installment_buyer_i_b7720d_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['status'], name='installment_status_6a3cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['next_due_date'], name='installment_next_du_332e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['installment_plan'], name='installment_install_ca1577_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['status'], name='installment_status_315c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['due_date'], name='installment_due_dat_36966f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installmentpayment',
            unique_together={('installment_plan', 'installment_number')},
        ),
    ]
