# Generated by Django 4.2.7 on 2025-12-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('shopkeeper', 'Shopkeeper'), ('buyer', 'Buyer'), ('admin', 'Admin')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='documents/cnic/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='documents/cnic/')),
                ('cnic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_license', models.ImageField(blank=True, null=True, upload_to='documents/licenses/')),
                ('default_installment_period', models.IntegerField(default=12)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopkeeper Profile',
                'verbose_name_plural': 'Shopkeeper Profiles',
                'db_table': 'shopkeeper_profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='documents/buyer_cnic/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='documents/buyer_cnic/')),
                ('cnic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_score', models.IntegerField(default=100)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopkeeper', models.ForeignKey(limit_choices_to={'user_type': 'shopkeeper'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
                'db_table': 'buyer_profiles',
                'indexes': [models.Index(fields=['shopkeeper'], name='buyer_profi_shopkee_4184c5_idx'), models.Index(fields=['is_blacklisted'], name='buyer_profi_is_blac_a0d8c4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
