# Generated by Django 6.1 on 2025-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='payment_methods',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
