# Generated by Django 4.2.7 on 2025-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
